# Generated by Django 4.2.19 on 2025-03-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
